language: cpp 

notifications:
 email: false

compiler:
 - g++

before_install:
 - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
 - sudo apt-get update -qq

install:
 - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq g++-4.8; fi
 - if [ "$CXX" == "g++" ]; then export CXX="g++-4.8"; fi
 - sudo apt-get install flex
 - sudo apt-get install bison
 - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50

script:
 - $CXX --version
 - make

